# Generated by Django 3.2.8 on 2021-10-22 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import materias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('tema', models.CharField(default='Tarea', max_length=45)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fechaLimite', models.DateField(blank=True, null=True)),
                ('materia_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_tarea', to='materias.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(default='Tema', max_length=45)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('archivo', models.FileField(blank=True, max_length=256, null=True, upload_to=materias.models.user_directory_path)),
                ('materia_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_tarea2', to='materias.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
