# Generated by Django 3.2.8 on 2021-10-20 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('tema', models.CharField(default='Tarea', max_length=45)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fechaLimite', models.DateField(blank=True, null=True)),
                ('materia_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_tarea', to='materias.materia')),
            ],
        ),
    ]
