# Generated by Django 3.2.8 on 2021-10-22 00:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import materias.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema2', models.CharField(default='Tema', max_length=45)),
                ('comentario2', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha2', models.DateField(default=datetime.date.today)),
                ('archivo2', models.FileField(blank=True, max_length=256, null=True, upload_to=materias.models.user_directory_path)),
                ('materia_tarea2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_tarea2', to='materias.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
