# Generated by Django 3.2.8 on 2021-10-22 07:24

from django.db import migrations, models
import materias.models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=materias.models.user_directory_path),
        ),
    ]
