# Generated by Django 3.2.8 on 2021-11-18 07:58

from django.db import migrations, models
import materias.models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_alter_tarea_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=materias.models.user_directory_path),
        ),
    ]
