# Generated by Django 3.2.8 on 2021-10-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_respuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='archivo2',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='comentario2',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='fecha2',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='materia_tarea2',
            new_name='materia_tarea',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='tema2',
            new_name='tema',
        ),
    ]
